# Generated by Django 5.2.4 on 2025-07-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigroup',
            name='analysis',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aigroup',
            name='answer',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aigroup',
            name='content',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aigroup',
            name='if_use',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aigroup',
            name='kind',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
